console.log("========================================== ")
console.log("            Selamat Datanng                ")
console.log("Perkenalkan Saya Si-Nod robot asisten  Kamu")
console.log("Silahkan Input Username :  ")
console.log("Silahkan Input password : *****")
console.log("Program ini ditujukan untuk meramaikan event)
console.log("========================================== ")
